name: build

on:
  push:
    branches:
      - master
      - ci
      - 'release/**'
  pull_request:
    branches: [master]

jobs:
  mingw:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        target: [x86_64-w64-mingw32]
    steps:
      - uses: actions/checkout@v3

      # Increase -N suffix here to force full rebuild after changes
      - uses: actions/cache@v3
        with:
          path: mingw_prefix/
          key: "${{ matrix.target }}-6"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake pkg-config g++-mingw-w64 gcc-multilib meson nasm
          ./bootstrap.py

      - name: Build with waf
        run: |
          ./ci/build-mingw64.sh waf configure --help >./build/help.txt
        env:
          TARGET: ${{ matrix.target }}

      - name: Print waf log
        run: |
          cat ./build/help.txt
